### PR TITLE
Neffos C7

### PR DESCRIPTION
**Pull request by NeonzGamingYT**

### CODE REVIEW

**Comment by Imshubh69** [comment]
@NeonzGamingYT

**Comment by jauharii** [comment]
@NeonzGamingYT hm

**Comment by Imshubh69** [comment]
@jauharii Bruhhhhhh

**Comment by jauharii** [comment]
@Imshubh69 oh no it's him

**Comment by Imshubh69** [comment]
@jauharii Fuck you

**Pull request closed without merging**
