### PR TITLE
Redmi 10

### PR DESCRIPTION
**Pull request by NeonzGamingYT**
selene boi

### CODE REVIEW

**Comment by jauharii** [comment]
@NeonzGamingYT oh boi

**Comment by NeonzGamingYT** [comment]
@jauharii stress

**Comment by el0xren** [comment]
@NeonzGamingYT stress

**Comment by NeonzGamingYT** [comment]
@el0xren lol

**Comment by el0xren** [comment]
@NeonzGamingYT lolol

**Comment by NeonzGamingYT** [comment]
@el0xren

**Pull request closed without merging**
